### ISSUE TITLE
Committee Styling, Change Font

### ISSUE THREAD

**Issue by mei-lu** [UMCP-CSA/Lunar-Banquet-2020#45]
- Change font to Open Sans for the position titles
- Use a heavier 600-700 Font weight of Open Sans for the member names (aka bold!)
- Round the picture corners
- Make components slightly smaller by adjusting image size

**Comment by nicholas-zhou** [comment]
Change font to Open Sans for the position titles
Use a heavier 600-700 Font weight of Open Sans for the member names (aka bold!)
Round the picture corners
Make components slightly smaller by adjusting image size
